// tarot.js
// 原神アルカナ22枚（大アルカナ全て）

export const omikujiFolder = location.hostname === 'localhost' || location.hostname === '127.0.0.1'
  ? '/99_SharedImage/01_Genshin/Omikuji/'
  : 'https://cdn.jsdelivr.net/gh/uko05/99_SharedImage@main/01_Genshin/Omikuji/';

export const CARD_BACK = `${omikujiFolder}back.png`;

export const tarotCards = [
  {
    id: 'fool', name: '愚者', nameEn: 'The Fool', number: '0',
    filename: `${omikujiFolder}Fool.png`,
    upright: { keyword: '自由・無限の可能性・新出発', message: '今日は何も恐れず一歩踏み出すエネルギーに満ちた日。常識を超えた先に本当の自分がいる。', lucky: '新品のスニーカー' },
    reversed: { keyword: '無謀・準備不足・無責任', message: '勢いだけで動くのは危険な日。少し立ち止まって、リスクを確認してから進もう。', lucky: 'チェックリスト' },
    upright_en: { keyword: 'Freedom · Infinite possibilities · New beginning', message: "Today is filled with the energy to take a step forward without fear. Your true self lies just beyond the boundaries of convention.", lucky: 'A brand-new pair of shoes' },
    reversed_en: { keyword: 'Recklessness · Lack of preparation · Irresponsibility', message: "Acting on impulse alone is risky today. Pause, check the risks carefully, and then move forward.", lucky: 'A checklist' },
  },
  {
    id: 'magician', name: '魔術師', nameEn: 'The Magician', number: 'I',
    filename: `${omikujiFolder}Magician.png`,
    upright: { keyword: '新たな始まり・意志・才能', message: '今日はあなたの中に眠る才能が輝きを放つ日。新しい挑戦に踏み出す意志が、道を切り拓く。', lucky: '筆記用具' },
    reversed: { keyword: '才能の停滞・焦り・空回り', message: '力はあるのに空回りしている状態。今日は焦らず、まず足元を見つめ直そう。', lucky: '深呼吸の時間' },
    upright_en: { keyword: 'New beginnings · Willpower · Talent', message: "Today is the day the talent within you shines forth. The will to take on new challenges carves out your path.", lucky: 'Stationery' },
    reversed_en: { keyword: 'Stagnating talent · Impatience · Spinning your wheels', message: "You have the ability, but it's misfiring right now. Today, slow down and take a good look at the ground beneath your feet.", lucky: 'Time to take a deep breath' },
  },
  {
    id: 'high_priestess', name: '女教皇', nameEn: 'The High Priestess', number: 'II',
    filename: `${omikujiFolder}High_Priestess.png`,
    upright: { keyword: '直感・内なる知恵・静観', message: '今日は直感が研ぎ澄まされている。論理より感覚を信じて動くと、思わぬ真実にたどり着く。', lucky: '日記' },
    reversed: { keyword: '情報不足・迷い・隠し事', message: 'まだ見えていない情報がある。今日は決断を急がず、もう少し状況を見守ろう。', lucky: '静かな場所' },
    upright_en: { keyword: 'Intuition · Inner wisdom · Observation', message: "Your intuition is finely tuned today. Trust your senses over logic, and you'll arrive at an unexpected truth.", lucky: 'A journal' },
    reversed_en: { keyword: 'Lack of information · Uncertainty · Hidden matters', message: "There is still information you haven't seen. Don't rush to a decision today — watch the situation unfold a little longer.", lucky: 'A quiet place' },
  },
  {
    id: 'empress', name: '女帝', nameEn: 'The Empress', number: 'III',
    filename: `${omikujiFolder}Empress.png`,
    upright: { keyword: '豊かさ・創造性・繁栄', message: '今日は豊かさのエネルギーに満ちた日。感性を活かした行動が実を結ぶ。', lucky: '花' },
    reversed: { keyword: '依存・停滞・過保護', message: '誰かに頼りすぎていないか振り返ろう。自分の力で一歩踏み出すことが大切な日。', lucky: '新鮮な食べ物' },
    upright_en: { keyword: 'Abundance · Creativity · Prosperity', message: "Today is a day brimming with the energy of abundance. Actions that draw on your senses will bear fruit.", lucky: 'Flowers' },
    reversed_en: { keyword: 'Dependence · Stagnation · Over-protection', message: "Reflect on whether you're relying too heavily on others. Taking your own step forward is what today calls for.", lucky: 'Fresh food' },
  },
  {
    id: 'emperor', name: '皇帝', nameEn: 'The Emperor', number: 'IV',
    filename: `${omikujiFolder}Emperor.png`,
    upright: { keyword: '安定・権威・秩序', message: '今日は安定と秩序の日。計画通りに動けば、着実に成果が積み上がる。', lucky: '手帳' },
    reversed: { keyword: '頑固・支配・硬直', message: '自分のやり方に固執しすぎているかもしれない。柔軟さが今日のカギ。', lucky: '散歩' },
    upright_en: { keyword: 'Stability · Authority · Order', message: "Today is a day of stability and order. Move according to your plan, and results will steadily accumulate.", lucky: 'A planner' },
    reversed_en: { keyword: 'Stubbornness · Control · Rigidity', message: "You may be clinging too tightly to your own way of doing things. Flexibility is the key to today.", lucky: 'A walk' },
  },
  {
    id: 'hierophant', name: '聖職者', nameEn: 'The Hierophant', number: 'V',
    filename: `${omikujiFolder}Hierophant.png`,
    upright: { keyword: '信念・導き・学び', message: '今日は誰かの言葉や教えが心に響く日。素直に受け取ることで新しい視野が開ける。', lucky: '本' },
    reversed: { keyword: '因習・独断・形式主義', message: '古いルールや他人の意見に縛られすぎていないか。今日は自分の軸で判断しよう。', lucky: '音楽' },
    upright_en: { keyword: 'Belief · Guidance · Learning', message: "Today is a day when someone's words or teachings resonate deeply. Receiving them openly widens your perspective.", lucky: 'A book' },
    reversed_en: { keyword: 'Dogma · Dogmatism · Formalism', message: "Are you too bound by old rules or others' opinions? Trust your own inner compass to make decisions today.", lucky: 'Music' },
  },
  {
    id: 'lovers', name: '恋人', nameEn: 'The Lovers', number: 'VI',
    filename: `${omikujiFolder}Lovers.png`,
    upright: { keyword: '愛・調和・大切な選択', message: '心と心が通じ合う予感のある日。大切な人との時間を丁寧に過ごそう。', lucky: 'ペアのもの' },
    reversed: { keyword: '不調和・迷い・誘惑', message: '感情が揺れやすい日。大きな決断は今日でなくてもいい。', lucky: '一人の時間' },
    upright_en: { keyword: 'Love · Harmony · An important choice', message: "A day with a sense of heart-to-heart connection. Spend time carefully with the people who matter most.", lucky: 'Something that comes in a pair' },
    reversed_en: { keyword: 'Discord · Indecision · Temptation', message: "Your emotions may be wavering today. There's no need to make a major decision right now.", lucky: 'Time alone' },
  },
  {
    id: 'chariot', name: '戦車', nameEn: 'The Chariot', number: 'VII',
    filename: `${omikujiFolder}Chariot.png`,
    upright: { keyword: '勝利・前進・意志力', message: '今日は勢いに乗れる日。目標に向かって迷いなく突き進もう。勝機は行動の中にある。', lucky: 'スポーツシューズ' },
    reversed: { keyword: '暴走・方向喪失・焦り', message: 'スピードを出しすぎているかもしれない。立ち止まって方向を確認しよう。', lucky: '地図' },
    upright_en: { keyword: 'Victory · Forward momentum · Willpower', message: "Today is a day to ride the momentum. Push toward your goal without hesitation. Your opportunity lies within your actions.", lucky: 'Athletic shoes' },
    reversed_en: { keyword: 'Runaway · Loss of direction · Impatience', message: "You may be moving too fast. Stop and double-check your direction.", lucky: 'A map' },
  },
  {
    id: 'strength', name: '力', nameEn: 'Strength', number: 'VIII',
    filename: `${omikujiFolder}Strength.png`,
    upright: { keyword: '勇気・忍耐・内なる強さ', message: '今日の強さは、穏やかさの中にある。感情をコントロールしながら前を向こう。', lucky: 'お守り' },
    reversed: { keyword: '自己不信・弱気・感情的', message: '自分を過小評価していないか。あなたにはもっと力がある。今日は自分を信じて。', lucky: '鏡' },
    upright_en: { keyword: 'Courage · Patience · Inner strength', message: "Today, true strength is found in calmness. Keep your emotions in check as you face forward.", lucky: 'An amulet' },
    reversed_en: { keyword: 'Self-doubt · Timidity · Emotionality', message: "You may be underselling yourself. You have more strength than you realize. Believe in yourself today.", lucky: 'A mirror' },
  },
  {
    id: 'hermit', name: '隠者', nameEn: 'The Hermit', number: 'IX',
    filename: `${omikujiFolder}Hermit.png`,
    upright: { keyword: '内省・孤独・知恵', message: '今日は内側に向かう日。静かな時間を確保して、自分の本音と向き合おう。', lucky: 'キャンドル' },
    reversed: { keyword: '孤立・引きこもり・頑固', message: '殻に閉じこもりすぎていないか。少し外に目を向けると光が見えてくる。', lucky: '友人へのメッセージ' },
    upright_en: { keyword: 'Introspection · Solitude · Wisdom', message: "Today is a day to turn inward. Carve out quiet time to face your true feelings honestly.", lucky: 'A candle' },
    reversed_en: { keyword: 'Isolation · Withdrawal · Stubbornness', message: "Are you shutting yourself away too much? Turning your gaze outward just a little brings the light back.", lucky: 'A message to a friend' },
  },
  {
    id: 'wheel_of_fortune', name: '運命の輪', nameEn: 'Wheel of Fortune', number: 'X',
    filename: `${omikujiFolder}Wheel_of_Fortune.png`,
    upright: { keyword: '転機・幸運・変化', message: '今日は流れが変わる予感がある日。チャンスは突然やってくる。アンテナを張っておこう。', lucky: 'コイン' },
    reversed: { keyword: '停滞・不運・変化への抵抗', message: '流れに逆らわず、今は待ちの姿勢が吉。焦らず次の波を待とう。', lucky: 'お茶' },
    upright_en: { keyword: 'Turning point · Good fortune · Change', message: "A sense that the tide is turning today. Opportunity comes without warning — keep your antenna up.", lucky: 'A coin' },
    reversed_en: { keyword: 'Stagnation · Bad luck · Resistance to change', message: "Rather than swimming against the current, a waiting posture is best for now. The next wave will come.", lucky: 'Tea' },
  },
  {
    id: 'justice', name: '正義', nameEn: 'Justice', number: 'XI',
    filename: `${omikujiFolder}Justice.png`,
    upright: { keyword: '公正・真実・バランス', message: '今日は誠実さが報われる日。正しいと思う行動を迷わず取ろう。', lucky: '白いもの' },
    reversed: { keyword: '不公平・偏見・責任逃れ', message: '自分に都合の良い解釈をしていないか振り返ろう。公平な目で状況を見つめ直して。', lucky: '天秤' },
    upright_en: { keyword: 'Fairness · Truth · Balance', message: "Today is a day when honesty is rewarded. Don't hesitate to do what you know is right.", lucky: 'Something white' },
    reversed_en: { keyword: 'Unfairness · Bias · Shirking responsibility', message: "Reflect on whether you're interpreting things in a way that's convenient for yourself. Try to see the situation with impartial eyes.", lucky: 'A pair of scales' },
  },
  {
    id: 'hanged_man', name: '吊るされた男', nameEn: 'The Hanged Man', number: 'XII',
    filename: `${omikujiFolder}Hanged_Man.png`,
    upright: { keyword: '待機・新しい視点・悟り', message: '今日は視点を変えると答えが見えてくる日。じっくり待つことも大切な選択。', lucky: '逆さに読める本' },
    reversed: { keyword: '停滞・無駄な犠牲・煮え切らない', message: 'いつまでも宙ぶらりんな状態を続けていないか。小さな決断から始めてみよう。', lucky: '新しいルート' },
    upright_en: { keyword: 'Waiting · A new perspective · Enlightenment', message: "Changing your viewpoint reveals the answer today. Sometimes, quietly waiting is the most important choice.", lucky: 'A book read from a different angle' },
    reversed_en: { keyword: 'Stagnation · Pointless sacrifice · Indecisiveness', message: "Are you still stuck in limbo? Starting with one small decision can begin to move things forward.", lucky: 'A new route' },
  },
  {
    id: 'death', name: '死神', nameEn: 'Death', number: 'XIII',
    filename: `${omikujiFolder}Death.png`,
    upright: { keyword: '終わりと始まり・変容・手放す', message: '今日は何かを手放すことで新しい扉が開く日。終わりを恐れず、変化を受け入れよう。', lucky: '古いものの整理' },
    reversed: { keyword: '変化への抵抗・執着・停滞', message: '手放せないものに縛られていないか。変化を拒むことで逆に苦しくなっている。', lucky: '断捨離' },
    upright_en: { keyword: 'Endings and beginnings · Transformation · Letting go', message: "Today, releasing something opens a new door. Don't fear endings — welcome the change.", lucky: 'Clearing out the old' },
    reversed_en: { keyword: 'Resistance to change · Attachment · Stagnation', message: "Are you bound by something you're unable to let go of? Resisting change may be making things harder.", lucky: 'Decluttering' },
  },
  {
    id: 'temperance', name: '節制', nameEn: 'Temperance', number: 'XIV',
    filename: `${omikujiFolder}Temperance.png`,
    upright: { keyword: 'バランス・調和・忍耐', message: '今日は焦らず、ゆっくりと調和を保ちながら進む日。急ぎすぎないことが最大の近道。', lucky: 'ハーブティー' },
    reversed: { keyword: '過剰・不調和・焦り', message: 'やりすぎていることがないか見直そう。今日は引き算の発想が大切。', lucky: '休憩時間' },
    upright_en: { keyword: 'Balance · Harmony · Patience', message: "Today is a day to move forward without rushing, keeping harmony. Not forcing the pace is the true shortcut.", lucky: 'Herbal tea' },
    reversed_en: { keyword: 'Excess · Disharmony · Impatience', message: "Check if you're overdoing anything. The spirit of subtraction is important today.", lucky: 'Break time' },
  },
  {
    id: 'devil', name: '悪魔', nameEn: 'The Devil', number: 'XV',
    filename: `${omikujiFolder}Devil.png`,
    upright: { keyword: '執着・誘惑・束縛', message: '今日は何かに縛られていないか確認の日。手放す勇気が自由をもたらす。', lucky: '換気' },
    reversed: { keyword: '解放・気づき・自由', message: '長らく縛られていたものから解放されるきっかけが来る日。その気づきを大切に。', lucky: '開けた場所' },
    upright_en: { keyword: 'Attachment · Temptation · Bondage', message: "Today is a day to check whether you are bound by something. The courage to let go brings freedom.", lucky: 'Ventilation' },
    reversed_en: { keyword: 'Liberation · Awareness · Freedom', message: "A trigger to be freed from what has long held you comes today. Treasure that moment of awareness.", lucky: 'An open space' },
  },
  {
    id: 'tower', name: '塔', nameEn: 'The Tower', number: 'XVI',
    filename: `${omikujiFolder}Tower.png`,
    upright: { keyword: '崩壊・突然の変化・解放', message: '予想外の出来事が起きるかもしれないが、それは新しい基盤を作るための変化。動じずに受け止めよう。', lucky: '柔軟な靴' },
    reversed: { keyword: '変化の回避・内的崩壊・先延ばし', message: '避け続けていたことと向き合う時が来ている。小さな崩壊で済むうちに対処しよう。', lucky: '素直な心' },
    upright_en: { keyword: 'Collapse · Sudden change · Liberation', message: "Something unexpected may happen, but it's a change to build a new foundation. Face it without being shaken.", lucky: 'Flexible shoes' },
    reversed_en: { keyword: 'Avoiding change · Inner collapse · Procrastination', message: "The time has come to face something you've been putting off. Better to deal with it while the damage is still small.", lucky: 'An open heart' },
  },
  {
    id: 'star', name: '星', nameEn: 'The Star', number: 'XVII',
    filename: `${omikujiFolder}Star.png`,
    upright: { keyword: '希望・癒し・インスピレーション', message: '今日は希望の光が差し込む日。素直な気持ちで夢を描くと、不思議と道が開けてくる。', lucky: '星型のもの' },
    reversed: { keyword: '希望の喪失・自己不信・現実逃避', message: '希望を見失いかけているかもしれない。今日は小さな良いことに目を向けてみよう。', lucky: '空を見上げること' },
    upright_en: { keyword: 'Hope · Healing · Inspiration', message: "Today, a ray of hope shines in. Draw your dreams with an open heart, and the path will open in a wonderful way.", lucky: 'Something star-shaped' },
    reversed_en: { keyword: 'Loss of hope · Self-doubt · Escapism', message: "You may be losing sight of hope. Try to focus on the small good things around you today.", lucky: 'Looking up at the sky' },
  },
  {
    id: 'moon', name: '月', nameEn: 'The Moon', number: 'XVIII',
    filename: `${omikujiFolder}Moon.png`,
    upright: { keyword: '幻想・直感・潜在意識', message: '今日は見えない世界からのメッセージが届く日。夢や直感を大切にしよう。', lucky: 'ムーンストーン' },
    reversed: { keyword: '混乱・恐れ・誤解', message: '不安や恐れが判断を曇らせている。今日は事実だけを見るよう意識しよう。', lucky: '明るい場所' },
    upright_en: { keyword: 'Illusion · Intuition · The subconscious', message: "Today is a day when messages from the unseen world arrive. Pay attention to your dreams and intuitions.", lucky: 'Moonstone' },
    reversed_en: { keyword: 'Confusion · Fear · Misunderstanding', message: "Anxiety and fear may be clouding your judgment. Today, make a conscious effort to look only at the facts.", lucky: 'A bright place' },
  },
  {
    id: 'sun', name: '太陽', nameEn: 'The Sun', number: 'XIX',
    filename: `${omikujiFolder}Sun.png`,
    upright: { keyword: '成功・喜び・活力', message: '今日は最高の輝きを放てる日。自分らしく堂々と生きることで全てがうまく回る。', lucky: 'サングラス' },
    reversed: { keyword: '停滞・過信・エネルギー不足', message: '調子が出にくいかもしれないが、太陽の力は必ずある。焦らず光を待とう。', lucky: '日光浴' },
    upright_en: { keyword: 'Success · Joy · Vitality', message: "Today is the day you can shine at your brightest. Living boldly as yourself makes everything work out beautifully.", lucky: 'Sunglasses' },
    reversed_en: { keyword: 'Stagnation · Overconfidence · Low energy', message: "You may feel off today, but the sun's power is always there. Wait for the light without rushing.", lucky: 'Sunbathing' },
  },
  {
    id: 'judgement', name: '審判', nameEn: 'Judgement', number: 'XX',
    filename: `${omikujiFolder}Judgement.png`,
    upright: { keyword: '覚醒・再生・呼びかけ', message: '今日は本当の自分に気づく日。過去を清算し、新しい自分として生まれ変わるチャンス。', lucky: 'トランペットの音' },
    reversed: { keyword: '自己批判・過去への執着・決断の先延ばし', message: '過去の失敗にとらわれすぎていないか。自分を許すことが今日の一番の課題。', lucky: '許しの言葉' },
    upright_en: { keyword: 'Awakening · Rebirth · A calling', message: "Today is the day to discover your true self. Clear away the past and seize the chance to be born anew.", lucky: 'The sound of a trumpet' },
    reversed_en: { keyword: 'Self-criticism · Clinging to the past · Postponing decisions', message: "Are you still haunted by past failures? Forgiving yourself is the greatest task for today.", lucky: 'Words of forgiveness' },
  },
  {
    id: 'world', name: '世界', nameEn: 'The World', number: 'XXI',
    filename: `${omikujiFolder}World.png`,
    upright: { keyword: '完成・達成・統合', message: '今日は一つの完成を迎える記念すべき日。積み重ねてきたものが結実する瞬間を楽しもう。', lucky: '地球儀' },
    reversed: { keyword: '未完成・達成感の欠如・先送り', message: 'もう少しで完成なのに踏み切れていないかもしれない。最後の一歩を踏み出そう。', lucky: 'ゴールテープ' },
    upright_en: { keyword: 'Completion · Achievement · Integration', message: "Today is a memorable day marking the completion of something. Enjoy the moment as everything you have built comes to fruition.", lucky: 'A globe' },
    reversed_en: { keyword: 'Incompletion · Lack of fulfillment · Procrastination', message: "You may be close to the finish line but unable to take the final leap. Go ahead and take that last step.", lucky: 'A finish-line ribbon' },
  },

  // ===== 激レアアルカナ（index 22・23 / 正位置のみ） =====
  {
    id: 'rare_bad', name: '奈落のアルカナ', nameEn: 'Arcana of the Abyss', number: '???',
    filename: `${omikujiFolder}rare_Bad.png`,
    isRare: true,
    upright: { keyword: '試練・深淵・宿命の刻', message: '深い闇の中にこそ、本物の光が宿る。今日という日は、あなたの魂が試されている。逃げるのではなく、正面から向き合え。この試練を乗り越えた先に、真の強さが待っている。', lucky: '折れない心' },
    reversed: { keyword: '試練・深淵・宿命の刻', message: '深い闇の中にこそ、本物の光が宿る。今日という日は、あなたの魂が試されている。逃げるのではなく、正面から向き合え。この試練を乗り越えた先に、真の強さが待っている。', lucky: '折れない心' },
    upright_en: { keyword: 'Trial · Abyss · Hour of Fate', message: "Within the deepest darkness, true light resides. Today is the day your soul is being tested. Do not flee — face it head-on. Beyond this trial, your true strength awaits.", lucky: 'An unbroken spirit' },
    reversed_en: { keyword: 'Trial · Abyss · Hour of Fate', message: "Within the deepest darkness, true light resides. Today is the day your soul is being tested. Do not flee — face it head-on. Beyond this trial, your true strength awaits.", lucky: 'An unbroken spirit' },
  },
  {
    id: 'rare_good', name: '七星のアルカナ', nameEn: 'Arcana of Seven Stars', number: '★',
    filename: `${omikujiFolder}rare_Good.png`,
    isRare: true,
    upright: { keyword: '奇跡・祝福・星の恵み', message: '七つの星が一線に並んだ奇跡の日。今日のあなたには、いつもと違う特別な風が吹いている。何をしても運が味方する——恐れず、思い切って動き出そう。', lucky: '七色の何か' },
    reversed: { keyword: '奇跡・祝福・星の恵み', message: '七つの星が一線に並んだ奇跡の日。今日のあなたには、いつもと違う特別な風が吹いている。何をしても運が味方する——恐れず、思い切って動き出そう。', lucky: '七色の何か' },
    upright_en: { keyword: 'Miracle · Blessing · Grace of the Stars', message: "A miraculous day when seven stars align in one line. A special breeze unlike any other blows toward you today. Luck is on your side in all things — be bold and make your move.", lucky: 'Something of seven colors' },
    reversed_en: { keyword: 'Miracle · Blessing · Grace of the Stars', message: "A miraculous day when seven stars align in one line. A special breeze unlike any other blows toward you today. Luck is on your side in all things — be bold and make your move.", lucky: 'Something of seven colors' },
  },
];
